services:
  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_cluster
      - CASSANDRA_NUM_TOKENS=256
    volumes:
      - ./cassandra_data:/data/cassandra

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

volumes:
  cassandra_data:
  redis_data: